//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Adobe_Gen.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.85.32.78:8080/soap/services/ETR/etr_forms")]
        public string WS_Adobe_Gen_etr_forms_ETR_etr_formsService {
            get {
                return ((string)(this["WS_Adobe_Gen_etr_forms_ETR_etr_formsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.85.32.78:8080/soap/services/ETR/Add_header_footer")]
        public string WS_Adobe_Gen_Add_header_footer_ETR_Add_header_footerService {
            get {
                return ((string)(this["WS_Adobe_Gen_Add_header_footer_ETR_Add_header_footerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.85.32.78:8080/soap/services/ETR/Add_watermark")]
        public string WS_Adobe_Gen_Add_watermark_ETR_Add_watermarkService {
            get {
                return ((string)(this["WS_Adobe_Gen_Add_watermark_ETR_Add_watermarkService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.85.32.78:8080/soap/services/ETR/konverze_DA")]
        public string WS_Adobe_Gen_konverze_DA_ETR_konverze_DAService {
            get {
                return ((string)(this["WS_Adobe_Gen_konverze_DA_ETR_konverze_DAService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.85.32.78:8080/soap/services/ETR/etr_konverze_pdfa")]
        public string WS_Adobe_Gen_etr_konverze_pdfa_ETR_etr_konverze_pdfaService {
            get {
                return ((string)(this["WS_Adobe_Gen_etr_konverze_pdfa_ETR_etr_konverze_pdfaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.85.68.11/ltd/ltd.asmx")]
        public string WS_Adobe_Gen_LTD_LTDWebService {
            get {
                return ((string)(this["WS_Adobe_Gen_LTD_LTDWebService"]));
            }
        }
    }
}
